### ISSUE TITLE
using class save_images(path) will always save to cwd if single image

### ISSUE THREAD

**Issue by Mycah** [jtara1/imgur-downloader#13]
Using save_images(path) in a class, if the imgur url is a single image it will save in the path the script is being run from instead of path

It works as defined if there are multiple images in the album.

**Comment by rachmadaniHaryono** [comment]
hi @Mycah , i have made pr to fix this, can you try if this fix program behaviour. thank you

**Comment by Mycah** [comment]
Works great now, thanks!
