### ISSUE TITLE
Can't parse image IDs in an album due to extensions

### ISSUE THREAD

**Issue by mheppner** [jtara1/imgur-downloader#16]
Using `imgur-downloader==0.1.7` with Python 3.6, downloading albums seems to be broken when image extensions have query params (versions?). Tested using [this album](https://imgur.com/a/Ra7yq). I think [this regex](https://github.com/jtara1/imgur_downloader/blob/0.1.7/imgur_downloader/imgurdownloader.py#L221) breaks since the extensions on that page are all `.jpg?1`. Other albums seem to work as expected.

Is there any reason why a regex is used instead of parsing it with JSON?

**Comment by jtara1** [comment]
6cb06f4aea47c76441adfb5eb5c8bd909fb55f3f

parsing json instead of using regex to match text was already implemented, just a small bug fixed so test cases pass now
