### ISSUE TITLE
imgur changed layout

### ISSUE THREAD

**Issue by Mycah** [jtara1/imgur-downloader#18]
Doesn't look like this returns anything anymore, which renders any album related downloads non functional:

search = re.search('(item:.*?};)', html, flags=re.DOTALL)

**Comment by jtara1** [comment]
make sure you're running the latest version, 

`pip3 install -U --user imgur-downloader`

or `git pull` if it's not installed and you're running directly

**Comment by Mycah** [comment]
Same exact query works now with no changes on my end.  imgur maybe reverted an update?
