### ISSUE TITLE
save_images doesn't work for folder after updating

### ISSUE THREAD

**Issue by Mycah** [jtara1/imgur-downloader#19]
I updated to the newest git version, and now save_images doesn't work with folder names with an album.

e.g:

downloader = ImgurDownloader("https://imgur.com/a/gjzrH")
downloader.save_images("folder")

This creates the folder "Fort 1 (gjzrH)" instead of "folder"

**Comment by jtara1** [comment]
I'm guessing it prioritizes using folder name passed in constructor call instead of save_images which doesn't make sense, or maybe this is a bug. I'll check in min.

**Comment by Mycah** [comment]
thanks. looks good.
