### ISSUE TITLE
Add file extension to name of save files

### ISSUE THREAD

**Issue by jtara1** [jtara1/imgur-downloader#9]
Tested this out of windows, can't open most images b/c their not saved with the extension in the name.

edit: doesn't seem to be a problem with images in albums or .gifv / .mp4 files downloaded

**Comment by rachmadaniHaryono** [comment]
Example url? 

Maybe add logging system and logging to file.

**Comment by jtara1** [comment]
My mistake, I think this was actually an issue with another project of mine that used imgur_downloader as a module/git-module.
